// services/nodeManager.js
// Wanderer mode — local capstashd node management
// Handles config file creation and node lifecycle

import { Platform } from 'react-native';
import RNFS from 'react-native-fs';

// These must match WANDERER_NODE_CONFIG in appMode.js exactly
const RPC_USER     = 'capstash';
const RPC_PASS     = 'localnode';
const RPC_PORT     = 8332;
const KNOWN_PEERS  = [
  'bitcoinii.ddns.net:9999',
];

// ── Paths ──────────────────────────────────────────────────────────────────
// Android filesDir — private to the app, survives reboots
export function getDataDir() {
  if (Platform.OS === 'android') {
    return '/data/user/0/com.capstashwallet/files/capstash';
  }
  return null;
}

export function getConfPath() {
  return `${getDataDir()}/capstash.conf`;
}

export function getBinaryPath() {
  return `${getDataDir()}/capstashd`;
}

// ── Config file ────────────────────────────────────────────────────────────
export async function writeNodeConfig() {
  const dataDir = getDataDir();
  const confPath = getConfPath();

  try {
    // Create data directory if it doesn't exist
    const exists = await RNFS.exists(dataDir);
    if (!exists) {
      await RNFS.mkdir(dataDir);
      console.log('[nodeManager] created data dir:', dataDir);
    }

    const confContent = [
      '# CapStash Wanderer Node Config',
      '# Auto-generated by CapStash wallet',
      '',
      'server=1',
      `rpcuser=${RPC_USER}`,
      `rpcpassword=${RPC_PASS}`,
      `rpcport=${RPC_PORT}`,
      'rpcallowip=127.0.0.1',
      'rpcbind=127.0.0.1',
      '',
      '# Known peers for fast sync',
      ...KNOWN_PEERS.map(p => `addnode=${p}`),
      '',
      '# Performance',
      'dbcache=64',
      'maxmempool=50',
      'prune=0',
    ].join('\n');

    await RNFS.writeFile(confPath, confContent, 'utf8');
    console.log('[nodeManager] config written to:', confPath);
    return true;

  } catch (e) {
    console.error('[nodeManager] writeNodeConfig failed:', e.message);
    return false;
  }
}

// ── Config reader — verify it exists ──────────────────────────────────────
export async function nodeConfigExists() {
  try {
    return await RNFS.exists(getConfPath());
  } catch (_) {
    return false;
  }
}

// ── First run setup ────────────────────────────────────────────────────────
export async function initWandererNode() {
  console.log('[nodeManager] initializing Wanderer node...');
  const written = await writeNodeConfig();
  if (written) {
    console.log('[nodeManager] node config ready at:', getConfPath());
    console.log('[nodeManager] next step: start capstashd binary');
  }
  return written;
}